# node version
FROM mhart/alpine-node:6

# create app directory
RUN mkdir -p /usr/app
WORKDIR /usr/app

# add bash to the docker container
RUN apk add --update bash && rm -rf /var/cache/apk/*

# files

COPY mocha.opts /usr/app
COPY package.json /usr/app/
COPY index.js /usr/app/

# directories
ADD example /usr/app/example
ADD lib /usr/app/lib
ADD test /usr/app/test

RUN npm install
RUN npm test
